<?php

namespace AppBundle\Repository;

/**
 * CierreTarjetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CierreTarjetaRepository extends \Doctrine\ORM\EntityRepository
{
}
