<?php

namespace AppBundle\Repository;

/**
 * EmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
