<?php

namespace AppBundle\Repository;


/**
 * MotivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoRepository extends \Doctrine\ORM\EntityRepository
{
   
}
