<?php

namespace AppBundle\Repository;

/**
 * TerminalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaHistorialRepository extends \Doctrine\ORM\EntityRepository
{
}
