<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.doctrine.orm.db2_query_cache' shared service.

$this->services['doctrine_cache.providers.doctrine.orm.db2_query_cache'] = $instance = new \Doctrine\Common\Cache\ArrayCache();

$instance->setNamespace('sf_orm_db2_f78075672b81ea224799e283d682adda1b925e126ed8ae8b11683f9cfca6770a');

return $instance;
