<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.db2_connection' shared service.

$a = new \Doctrine\DBAL\Configuration();

$b = new \Doctrine\DBAL\Logging\LoggerChain();
$b->addLogger(${($_ = isset($this->services['doctrine.dbal.logger']) ? $this->services['doctrine.dbal.logger'] : $this->load('getDoctrine_Dbal_LoggerService.php')) && false ?: '_'});
$b->addLogger(${($_ = isset($this->services['doctrine.dbal.logger.profiling.db2']) ? $this->services['doctrine.dbal.logger.profiling.db2'] : ($this->services['doctrine.dbal.logger.profiling.db2'] = new \Doctrine\DBAL\Logging\DebugStack())) && false ?: '_'});

$a->setSQLLogger($b);
$c = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this);
$c->addEventListener([0 => 'loadClassMetadata'], ${($_ = isset($this->services['doctrine.orm.db2_listeners.attach_entity_listeners']) ? $this->services['doctrine.orm.db2_listeners.attach_entity_listeners'] : ($this->services['doctrine.orm.db2_listeners.attach_entity_listeners'] = new \Doctrine\ORM\Tools\AttachEntityListenersListener())) && false ?: '_'});

return $this->services['doctrine.dbal.db2_connection'] = ${($_ = isset($this->services['doctrine.dbal.connection_factory']) ? $this->services['doctrine.dbal.connection_factory'] : ($this->services['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory([]))) && false ?: '_'}->createConnection(['driver' => 'pdo_ibm_i', 'host' => NULL, 'port' => NULL, 'dbname' => NULL, 'user' => 'SRODAS', 'password' => 'samir2016', 'charset' => 'UTF8', 'driverOptions' => ['odbc' => 'PROD'], 'defaultTableOptions' => []], $a, $c, []);
