<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJerdj5h\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJerdj5h/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJerdj5h.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJerdj5h\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJerdj5h\appProdProjectContainer([
    'container.build_hash' => 'Jerdj5h',
    'container.build_id' => 'ec1873aa',
    'container.build_time' => 1632515297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJerdj5h');
