<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Services\mufService' shared service.

return $this->services['AppBundle\Services\mufService'] = new \AppBundle\Services\mufService(${($_ = isset($this->services['doctrine.orm.db2_entity_manager']) ? $this->services['doctrine.orm.db2_entity_manager'] : $this->load('getDoctrine_Orm_Db2EntityManagerService.php')) && false ?: '_'});
