<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sec.security.authentication.listener' shared service.

return $this->services['sec.security.authentication.listener'] = new \Comfamiliar\SeguridadBundle\Sec\SecListener(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['sec.security.authentication.provider']) ? $this->services['sec.security.authentication.provider'] : $this->load('getSec_Security_Authentication_ProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['sec.security.user.provider']) ? $this->services['sec.security.user.provider'] : $this->services['sec.security.user.provider'] = new \Comfamiliar\SeguridadBundle\Sec\SecUserProvider('sDgxtX8x0oVS84Dt79202927upRkG0B4', 173, false)) && false ?: '_'});
