<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.dao.login' shared service.

return $this->services['security.authentication.provider.dao.login'] = new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider(${($_ = isset($this->services['sec.security.user.provider']) ? $this->services['sec.security.user.provider'] : $this->services['sec.security.user.provider'] = new \Comfamiliar\SeguridadBundle\Sec\SecUserProvider('sDgxtX8x0oVS84Dt79202927upRkG0B4', 173, false)) && false ?: '_'}, new \Symfony\Component\Security\Core\User\UserChecker(), 'login', ${($_ = isset($this->services['security.encoder_factory']) ? $this->services['security.encoder_factory'] : $this->load('getSecurity_EncoderFactoryService.php')) && false ?: '_'}, true);
