<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sec.security.encoder' shared service.

return $this->services['sec.security.encoder'] = new \Comfamiliar\SeguridadBundle\Sec\SecEncoder();
