<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sec.security.authentication.provider' shared service.

return $this->services['sec.security.authentication.provider'] = new \Comfamiliar\SeguridadBundle\Sec\SecAuthenticationProvider(${($_ = isset($this->services['sec.security.user.provider']) ? $this->services['sec.security.user.provider'] : ($this->services['sec.security.user.provider'] = new \Comfamiliar\SeguridadBundle\Sec\SecUserProvider('sDgxtX8x0oVS84Dt79202927upRkG0B4', 173, false))) && false ?: '_'});
