<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQangid2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQangid2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQangid2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQangid2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQangid2\appDevDebugProjectContainer([
    'container.build_hash' => 'Qangid2',
    'container.build_id' => '8116de3e',
    'container.build_time' => 1652103559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQangid2');
