<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Terminal extends \AppBundle\Entity\Terminal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'idSec', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'idAlmacen', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'order', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'edcinFO', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'fecCreacion', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'fUltMod', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'printer', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'revenue'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'idSec', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'idAlmacen', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'order', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'edcinFO', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'fecCreacion', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'fUltMod', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'usuario', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'printer', '' . "\0" . 'AppBundle\\Entity\\Terminal' . "\0" . 'revenue'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Terminal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSec($idSec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSec', [$idSec]);

        return parent::setIdSec($idSec);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSec', []);

        return parent::getIdSec();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAlmacen($idAlmacen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAlmacen', [$idAlmacen]);

        return parent::setIdAlmacen($idAlmacen);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAlmacen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAlmacen', []);

        return parent::getIdAlmacen();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdcinFO($edcinFO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdcinFO', [$edcinFO]);

        return parent::setEdcinFO($edcinFO);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdcinFO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdcinFO', []);

        return parent::getEdcinFO();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecCreacion($fecCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecCreacion', [$fecCreacion]);

        return parent::setFecCreacion($fecCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecCreacion', []);

        return parent::getFecCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFUltMod($fUltMod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFUltMod', [$fUltMod]);

        return parent::setFUltMod($fUltMod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFUltMod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFUltMod', []);

        return parent::getFUltMod();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrinter($printer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrinter', [$printer]);

        return parent::setPrinter($printer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrinter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrinter', []);

        return parent::getPrinter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevenue($revenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevenue', [$revenue]);

        return parent::setRevenue($revenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenue', []);

        return parent::getRevenue();
    }

}
